import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod/v4";
import { generateText } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { readFileSync } from "node:fs";
import { extname } from "node:path";
import { createRequire } from "node:module";

// ─── Version from package.json ─────────────────────────────────

const require = createRequire(import.meta.url);
const { version } = require("../package.json") as { version: string };

// ─── Configuration from environment ───────────────────────────────

const VISION_API_KEY = process.env.VISION_API_KEY;
const VISION_BASE_URL =
  process.env.VISION_BASE_URL || "https://api.openai.com/v1";
const VISION_MODEL = process.env.VISION_MODEL || "mimo-v2.5";

if (!VISION_API_KEY) {
  console.error("ERROR: VISION_API_KEY environment variable is required");
  process.exit(1);
}

// ─── Media type detection ──────────────────────────────────────────

const MIME_MAP: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".bmp": "image/bmp",
  ".svg": "image/svg+xml",
  ".tiff": "image/tiff",
  ".tif": "image/tiff",
  ".ico": "image/x-icon",
  ".heic": "image/heic",
  ".heif": "image/heif",
};

function getMediaType(filePath: string): string | null {
  const ext = extname(filePath).toLowerCase();
  return MIME_MAP[ext] || null;
}

// ─── Detail-level prompts ──────────────────────────────────────────

const SYSTEM_PROMPTS: Record<string, string> = {
  brief:
    "You are a concise image describer. Reply in 1-2 short sentences. " +
    "Focus only on the most important subject and action in the image. " +
    "Be direct and brief.",

  standard:
    "You are a helpful image describer. Describe the image in detail — " +
    "cover main subjects, composition, colors, setting, and any notable elements. " +
    "Be thorough but focused. Do not add interpretation beyond what is visible.",

  detailed:
    "You are an expert visual analyst. Provide an extremely thorough, " +
    "comprehensive description. Cover: main subjects, background, composition, " +
    "lighting/contrast, colors/palette, textures, mood/atmosphere, " +
    "spatial relationships, any text visible (transcribe exactly), " +
    "and subtle details that might be overlooked. Be exhaustive.",
};

// ─── OpenAI client ─────────────────────────────────────────────────

const openai = createOpenAI({
  apiKey: VISION_API_KEY,
  baseURL: VISION_BASE_URL,
});

// ─── MCP Server ────────────────────────────────────────────────────

const server = new McpServer({
  name: "mcp-sight",
  version,
});

server.registerTool(
  "see_image",
  {
    title: "See Image",
    description: `Describe an image file using a vision-capable large language model.

Use this tool when the user sends an image or references an image on disk
and you need to understand its contents.

Args:
  - image_path (string, required): Absolute path to the image file on disk
  - prompt (string, optional): Specific question or instruction for the vision model.
      Defaults to "Describe this image in detail."
  - context (string, optional): Background context from the conversation.
      Helps the model understand what the user is ultimately trying to accomplish.
  - detail_level ("brief" | "standard" | "detailed", optional):
      Level of detail. Defaults to "standard".

Returns:
  Text description of the image contents generated by the vision model.

Examples:
  - User sends a screenshot and asks "what does this error mean?" ->
      image_path="/tmp/screenshot.png", context="user is debugging a crash", prompt="what does this error message say?"
  - User says "describe this photo" ->
      image_path="/home/user/photo.jpg"
  - User says "briefly, what's in this image?" ->
      image_path="/tmp/pic.png", detail_level="brief"

Supported formats: JPEG, PNG, GIF, WebP, BMP, SVG, TIFF, ICO, HEIC, HEIF

Error Handling:
  - Returns error if file cannot be read (check path is absolute and file exists)
  - Returns error if file extension is not a supported image format
  - Returns error if vision API call fails (check VISION_API_KEY and VISION_BASE_URL)`,
    inputSchema: z.object({
      image_path: z
        .string()
        .describe(
          "Absolute path to the image file to describe (e.g. C:/Users/Admin/pic.png)"
        ),
      prompt: z
        .string()
        .optional()
        .describe(
          'Specific question or instruction for the vision model. Defaults to "Describe this image in detail."'
        ),
      context: z
        .string()
        .optional()
        .describe(
          "User's original question or background context. " +
            "This helps the model understand what the user is ultimately trying to accomplish."
        ),
      detail_level: z
        .enum(["brief", "standard", "detailed"])
        .optional()
        .describe(
          "Level of detail in the description. " +
            "'brief' = 1-2 sentences, 'standard' = thorough description, " +
            "'detailed' = exhaustive visual analysis. Defaults to 'standard'."
        ),
    }).strict(),
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
  },
  async ({ image_path, prompt, context, detail_level }) => {
    // 1. Read image file
    let buffer: Buffer;
    let mediaType: string;
    try {
      buffer = readFileSync(image_path);
      const detected = getMediaType(image_path);
      if (!detected) {
        const ext = extname(image_path).toLowerCase() || "(no extension)";
        return {
          content: [
            {
              type: "text" as const,
              text:
                `Unsupported image format "${ext}". ` +
                `Supported: JPEG, PNG, GIF, WebP, BMP, SVG, TIFF, ICO, HEIC, HEIF.`,
            },
          ],
          isError: true,
        };
      }
      mediaType = detected;
    } catch (err: unknown) {
      return {
        content: [
          {
            type: "text" as const,
            text:
              `Failed to read image file at "${image_path}": ${err instanceof Error ? err.message : String(err)}. ` +
              `Make sure the path is absolute and the file exists.`,
          },
        ],
        isError: true,
      };
    }

    // 2. Construct prompts
    const level = detail_level || "standard";
    const systemPrompt = SYSTEM_PROMPTS[level];

    let userPrompt = prompt || "Describe this image in detail.";
    if (context) {
      userPrompt = [
        "Background context (the user is asking about this):",
        context,
        "",
        "Specific request:",
        userPrompt,
      ].join("\n");
    }

    // 3. Call vision model
    try {
      const result = await generateText({
        model: openai.chat(VISION_MODEL),
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: userPrompt },
              { type: "image", image: buffer, mediaType },
            ],
          },
        ],
      });

      return {
        content: [{ type: "text" as const, text: result.text }],
      };
    } catch (err: unknown) {
      return {
        content: [
          {
            type: "text" as const,
            text:
              `Vision model API error: ${err instanceof Error ? err.message : String(err)}. ` +
              `Check that VISION_API_KEY and VISION_BASE_URL are configured correctly.`,
          },
        ],
        isError: true,
      };
    }
  }
);

// ─── Start ─────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`mcp-sight ready (model: ${VISION_MODEL}, base: ${VISION_BASE_URL})`);
}

main().catch((err: unknown) => {
  console.error("Fatal error starting mcp-sight:", err);
  process.exit(1);
});
